# Generated by Django 4.0.3 on 2022-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('presented_by', models.CharField(max_length=100, verbose_name='presented_by')),
                ('file', models.FileField(upload_to='sessions_file/', verbose_name='file')),
            ],
        ),
    ]
